packages:
  - "."
  - "packages/webhooks-mautic-zendesk"
  - "packages/cli-zendesk"
  - "packages/webhooks-solidarity-count"
  - "packages/listener-solidarity"
  - "packages/components"
  # - "packages/listener-match"
  # - "packages/cli-mautic"

